### ISSUE TITLE
need to update service provider path

### ISSUE THREAD

**Issue by pilishen** [rinvex/laravel-categories#10]
not a big problem, but when using under laravel 5.5, which haven't support package autodiscovering, the service provider path registered in `config/app.php` should be updated into :
```
Rinvex\Categorizable\Providers\CategorizableServiceProvider::class,
```
u see, it's now under `providers` folder

also need to update the readme page

thanks

**Comment by pilishen** [comment]
also in your related model, u should update the `category` model path and `categorizable` trait path:
```
use Rinvex\Categorizable\Models\Category;
use Rinvex\Categorizable\Traits\Categorizable;
```

**Comment by Omranic** [comment]
Please note that **master** branch is completely different than **develop** branch, and while the **develop** branch is the most updated, we will merge into **master** soon but will drop support for any Laravel versions less than v5.5
