### ISSUE TITLE
All ancestor options return a single parent only

### ISSUE THREAD

**Issue by deanzod** [rinvex/laravel-categories#106]
I've tried almost all of the ancestor options to display breadcrumbs of a 3 deep nested category and they all just show the parent. The root parent is never returned.

e.g.

```php
id  name    parent_id   
1   cat1      null
2   cat2      1
3   cat3      2

dd(app('rinvex.categories.category')->ancestorsOf(3);

```

This will return 3, related 2, but no related 1 - basically the same as  `->parent`

**Comment by Omranic** [comment]
I'm not sure I understand what's your issue exactly. Would you please explain your use case, what's the error, and what's the expected outcome, with code samples of your implementation. Feel free to re-open this issue.

Also as a reference, you can check the ancestors docs here https://github.com/rinvex/laravel-categories#retrieving-categories
