### ISSUE TITLE
Why is a custom queue name used?

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [rinvex/laravel-categories#107]
95d4d2364e78d7a5796afa70920d47883e9e2836 moved the events to a queue called `events`.  It is not documented anywhere that a custom queue is used for this package.

Can we set this back to default or document this?

**Comment by Omranic** [comment]
This is no longer applicable to the latest release v6+, all event related code has been removed as it's considered implementation details, and developers can customize it the way they want.
