### ISSUE TITLE
php 7.4 support

### ISSUE THREAD

**Issue by Cyvelnet** [rinvex/laravel-categories#108]
The package `spatie/laravel-sluggable` version 3.0.0 dropped php 7 support completely, which mean https://github.com/rinvex/laravel-categories/blob/1b7c92c1820285d335b97130f87146f39dfd8365/composer.json#L44 php7.4 support will never works, maybe a rollback to use version 2 is needed?

**Comment by Omranic** [comment]
@Cyvelnet if you need the new fixes, but with the old composer dependencies support (old PHP version too), you'll need to fork this package then, and change composer.json to your needs.

Currently we're supporting latest PHP/Laravel/Composer Dependencies releases only. In many cases you'll find a tag that you can lock your dependencies to, for example you can still use this package and lock it to this revision: 526cb66
