### ISSUE TITLE
[Question] Is there a way to get an array of all categories with their names, ids, & children?

### ISSUE THREAD

**Issue by ramtinq** [rinvex/laravel-categories#112]
Is there a way to get an array of all categories with their names, ids, & children like when we set them using the `create()` method? I mean something like this:

```
$allCategories = 
     [
        'name' => [
            'en' => 'Garden',
            'de' => 'Gartenا',
        ],
        'slug' => 'garden',
        'id' => 1,
        'children' => [
          [
            'name' => [
              'en' => 'Trees',
              'de' => 'Bäume',
            ],
            'slug' = 'trees',
            'id' => 2,
            'children' => [
               ...
            ],
        ],
       [
          'name' =>
             ...
       ],
       ...
        
    ];
```

Actually I want to build a json from it to be used in frontend menus.

Thanks for your great package.

**Comment by Omranic** [comment]
If I understand you correctly, it's easy to get all categories like that `app('rinvex.categories.category')->all()`

If that's not what you mean, feel free to re-open this issue and clarify what you need to achieve, and I'll be happy to assist.

Also consider checking the usage docs which is extensively detailed on how to use this package: https://github.com/rinvex/laravel-categories#usage
