### ISSUE TITLE
Cannot integrate to nova

### ISSUE THREAD

**Issue by nurmuhammet-ali** [rinvex/laravel-categories#113]
#### When I try creating from nova interface, I get `There was a problem submitting the form`
```php
    public function fields(Request $request)
    {
        return [
            ID::make(__('ID'), 'id')->sortable(),

            Text::make('Ady', 'Name')
                ->rules('required', 'string', 'strip_tags', 'max:150'),

            Textarea::make('Maglumat', 'Description'),
        ];
    }
```

**Comment by nurmuhammet-ali** [comment]
## And seems like the slack link is also open for on email address ending in @rinvex.com or @omranic.com
`This link is no longer active
If you have an email address ending in @rinvex.com or @omranic.com, you can join this workspace using that address. Otherwise, you’ll need to ask for a new link.`

**Comment by Omranic** [comment]
@nurmuhammet-ali  Thank you for your question, can you please explain what's exactly your problem?

Please provide more details on what steps you've taken, what's the error you're getting, and how to reproduce it.

Personally I don't use Nova, so I'm not sure I'll be able to test it, but at least will try to help based on your steps and error message. Also please make sure you've checked the documentation first here https://github.com/rinvex/laravel-categories#manage-your-categorizable-model

In regard to Slack, I'll fix it later. For now, you can post any issues here on GitHub.

Feel free to re-open for further discussion, happy to help 👍
