### ISSUE TITLE
Is there a way to retrieve models that belong to a category?

### ISSUE THREAD

**Issue by Fredericld** [rinvex/laravel-categories#115]
Hi,

I am building a page listing of bike parts that belongs certain categories.

I can list all the my parts using the following
```
$items = Part::select('id', 'name', 'uuid', 'oem_number')
```

but I would like to be able to filter the parts by category using something like this
```
$items = Part::select('id', 'name', 'uuid', 'oem_number')->thatBelongToAnyCategory([,1,2])
```

**Comment by Fredericld** [comment]
$items->whereHas('categories', function ($q) use ($categoriesList) {
                    $q->whereIn('id', $categoriesList);
                });

**Comment by Omranic** [comment]
Glad you got it, let me know if you need further help.
