### ISSUE TITLE
HasFactory trait missing from Category Model

### ISSUE THREAD

**Issue by Rattone** [rinvex/laravel-categories#118]
Hi! Is there a reason why the Category model doesn't have the HasFactory trait?
Can I create a class that extends Category and "use" the HasFactory trait? Is this the right way?
Thanks for the replies!

**Comment by Omranic** [comment]
Thank you for your suggestion, this has been pushed on `develop` branch here https://github.com/rinvex/laravel-categories/commit/1ba238f3b91c9dee80aea9cb300bada3f8dd2b0f

And yes, you can always override the default model and easily change the runtime model via configuration https://github.com/rinvex/laravel-categories/blob/master/config/config.php#L20
