### ISSUE TITLE
Support for Laravel 9

### ISSUE THREAD

**Issue by aryno** [rinvex/laravel-categories#120]
The package does not seem to support Laravel version 9.  Composer throws error when trying to upgrade.

**Comment by Omranic** [comment]
Thank you for your patience, this package has been now updated to support Laravel v9. Check the latest version v6.1.0

**Comment by FarhanShares** [comment]
I'm getting this error on Laravel 9.x & PHP 8.x

```
Problem 1
    - felixkiss/uniquewith-validator 3.4.2 requires illuminate/support ^5.5|^6.0|^7.0|^8.0 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - rinvex/laravel-support v6.1.0 requires felixkiss/uniquewith-validator dev-l9-compatibility -> found felixkiss/uniquewith-validator[dev-master, 1.0.0, ..., 1.1.4, 2.0.0, ..., 2.0.8, 3.0.0, ..., 3.4.2] but it does not match the constraint.
    - rinvex/laravel-categories v6.1.0 requires rinvex/laravel-support ^6.0.0 -> satisfiable by rinvex/laravel-support[v6.0.0, ..., v6.1.0].
    - rinvex/laravel-support[v6.0.0, ..., v6.0.3] require felixkiss/uniquewith-validator ^3.4.2 -> satisfiable by felixkiss/uniquewith-validator[3.4.2].
    - Root composer.json requires rinvex/laravel-categories ^6.1 -> satisfiable by rinvex/laravel-categories[v6.1.0].
```
    
  **One of the dependencies that is used by rinvex/laravel-categories has not updated yet to support Laravel 9.**
  https://github.com/felixkiss/uniquewith-validator/issues/132

**Comment by Omranic** [comment]
@FarhanShares Thanks, this is a known issue with one of the dependencies, please check the details and solution here https://github.com/rinvex/laravel-support#note-for-laravel-v9

**Comment by mattvb91** [comment]
@Omranic any chance of forking it and releasing as part of the rinvex scope or completely replacing it here cause that project is dead

**Comment by Omranic** [comment]
@mattvb91 who said the project is dead?!

It's interesting to say a project is dead, when you get immediate response in 2 mins of your post!

Anyway what's your issue exactly?

**Comment by mattvb91** [comment]
@Omranic im talking about `felixkiss/uniquewith-validator` not this project. Obviously I can see the releases and activity here :)

**Comment by Omranic** [comment]
That package has been replaced already by a temporary fork rinvex/tmp-felixkiss-uniquewith-validator

**Comment by mattvb91** [comment]
hmm im still getting:

```
    - rinvex/laravel-support[v6.1.0, ..., v6.1.3] require felixkiss/uniquewith-validator dev-l9-compatibility -> found felixkiss/uniquewith-validator[dev-master, 1.0.0, ..., 1.1.4, 2.0.0, ..., 2.0.8, 3.0.0, ..., 3.4.2] but it does not match the constraint.

```

with tag:

```
        "rinvex/laravel-categories": "v6.1.2",
```

**Comment by Omranic** [comment]
`{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/uniquewith-validator.git"
        }
    ]
}`

Have you added the above code on your project root composer.json?

Details https://github.com/rinvex/laravel-support#note-for-laravel-v9

**Comment by mattvb91** [comment]
ah thats exactly what i mean if it would be possible to fork that and keep it under the rinvex umbrella as using that will randomly trigger composer to require auth keys so we can remove that because not only does it cause issues locally but in the whole deployment process along the way if composer is getting throttled and I dont see that package getting updated again in future.

**Comment by Omranic** [comment]
Got it 👍 agreed, but that's another package to maintain which we don't have the bandwidth for, would love to see someone taking over that package maintenance.

**Comment by mattvb91** [comment]
> Got it +1 agreed, but that's another package to maintain which we don't have the bandwidth for, would love to see someone taking over that package maintenance.

yea i would definitely point out that its unmaintained and only there to get rid of the compatibility issue or maybe even archive it instantly but still just have that latest tag available.

**Comment by mattvb91** [comment]
@Omranic could you take a look at the following PR when you have time? https://github.com/rinvex/laravel-support/pull/66

**Comment by Omranic** [comment]
@mattvb91 In the time being, please follow the instructions here in order to make it work without issues https://github.com/rinvex/laravel-support#note-for-laravel-v9

**Comment by mattvb91** [comment]
> @mattvb91 In the time being, please follow the instructions here in order to make it work without issues https://github.com/rinvex/laravel-support#note-for-laravel-v9

This doesn't work if your pulling in automated CI tools because it requires composer auth tokens.

The PR is actually released on packagist so it resolves that whole issue

**Comment by Omranic** [comment]
I understand, thank you for your input. I’d still rather stick with the existing shift fork at the time being until there’s a more reliable solution. I agree it’s not perfect, but it is what it is. I hope this package could be maintained replaced one day.

**Comment by Omranic** [comment]
Update: we dropped the `felixkiss/uniquewith-validator` dependency 🙂 https://github.com/rinvex/laravel-support/commit/2bf69b8dcbf6f18ecd97c2c7b43ae441d58765cd
