### ISSUE TITLE
Always try to install rinvex/tmp-watson-validating from rinvex/support

### ISSUE THREAD

**Issue by forxer** [rinvex/laravel-categories#121]
In composer json: 

"rinvex/laravel-support": "^6.0.0",

should be:

"rinvex/laravel-support": "^6.1.0",

I think, if you follow SEMVER, it will be better like this:

"rinvex/laravel-support": "^6.0",

**Comment by Omranic** [comment]
Thank you @forxer, I think this is just a personal preference instead of a recommendation.

If you've a reference for more supporting this change, I would be happy to check 🙂

**Comment by forxer** [comment]
@Omranic you didn't understand

you [fix this laravel support issue](https://github.com/rinvex/laravel-support/issues/64)  in [this commit](https://github.com/rinvex/laravel-support/commit/9529075c6ec00158649cb2e305238d43b447d853)

and you've tagged rinvex/laravel-support 6.1.0

but here in rinvex/laravel-categories you require "rinvex/laravel-support": "^6.0.0"

so when we update this package we have the same problem because laravel support is not updated in 6.1.0 and stays in 6.0.0

**Comment by Omranic** [comment]
Well, that's not accurate. 

When using the caret `^` symbol for version constraints, it means it covers all patch and minor versions, so when requiring `^6.0.0` composer will install any versions prior to `^7.0.0`, including `v6.1.0` and `v6.9.0` and whatever in between.

Check the following reference for more details: https://getcomposer.org/doc/articles/versions.md#caret-version-range-

So in your case, most probably there is another package that's still not compatible with Laravel v9. which prevents composer from installing the correct versions. I hope that helps..

**Comment by forxer** [comment]
@Omranic Oh yes you are right!

I'm stupid, I forgot to add in my composer.json file:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/uniquewith-validator.git"
        }
    ]
}
```

It wasn't easy to find because I didn't have an explicit composer error regarding this package.
I had to install only Laravel and rinvex/categories to understand.

Maybe in addition to the note on rinvex/laravel-support it should be indicated in the readme of this package while waiting for the original package to be updated.

Thank you for your help :)

**Comment by Omranic** [comment]
No worries, glad it works now. Don't hesitate to reach out if you need any further help 🙂 

Here is a link to that update for reference in case anyone else got stuck in the same issue
https://github.com/rinvex/laravel-support#note-for-laravel-v9

Hopefully that PR get merged soon and we remove that workaround!
