### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by mattvb91** [rinvex/laravel-categories#122]
Looks like `rinvex/tmp-watson-validating` dependancy is locking to PHP 8.0.0 but not sure if the fork is still maintained?

**Comment by Omranic** [comment]
`rinvex/tmp-watson-validating` is no longer required in our package's latest version.

Make sure you're installing the latest release of `rinvex/categories` v6.1.0 or above.

**Comment by RomkaLTU** [comment]
Doesn't work, using "rinvex/laravel-categories": "^6.1.0" and still getting complains about php version from validating package.

**Comment by Omranic** [comment]
@RomkaLTU  What's not working, and what's the error message you're getting?

**Comment by RomkaLTU** [comment]
Later I discovered that I need to use laravel shift fork, as a workaround. It wasn't obvious from the documentation, the error was about PHP version support from the internal package.

**Comment by Omranic** [comment]
Glad it's now working, feel free to reach out if you've any other questions. Happy to help..
