### ISSUE TITLE
Requires illuminate/support ^5.5|^6.0|^7.0|^8.0 error on installing

### ISSUE THREAD

**Issue by Jacobtims** [rinvex/laravel-categories#123]
When I try to install laravel-categories (composer require rinvex/laravel-categories) I get this errror. How can I fix this?
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - felixkiss/uniquewith-validator 3.4.2 requires illuminate/support ^5.5|^6.0|^7.0|^8.0 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not load
> ed, likely because it conflicts with another require.
>     - rinvex/laravel-support v6.1.0 requires felixkiss/uniquewith-validator dev-l9-compatibility -> found felixkiss/uniquewith-validator[dev-master, 1.0.0, ..., 1.1.4, 2.0.0, ..., 2.0.8, 3.0.0, ..., 3.4.2] but it does not match the 
> constraint.
>     - rinvex/laravel-categories v6.1.0 requires rinvex/laravel-support ^6.0.0 -> satisfiable by rinvex/laravel-support[v6.0.0, ..., v6.1.0].
>     - rinvex/laravel-support[v6.0.0, ..., v6.0.3] require felixkiss/uniquewith-validator ^3.4.2 -> satisfiable by felixkiss/uniquewith-validator[3.4.2].
>     - Root composer.json requires rinvex/laravel-categories ^6.1 -> satisfiable by rinvex/laravel-categories[v6.1.0].
> 
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by Jacobtims** [comment]
I already fixed it by using this for Laravel 9: https://github.com/rinvex/laravel-support#note-for-laravel-v9

**Comment by Omranic** [comment]
Update: we dropped the `felixkiss/uniquewith-validator` dependency 🙂 https://github.com/rinvex/laravel-support/commit/2bf69b8dcbf6f18ecd97c2c7b43ae441d58765cd
