### ISSUE TITLE
invex/laravel-categories v6.1.0 with spatie/laravel-translatable 6.0

### ISSUE THREAD

**Issue by volkankaban** [rinvex/laravel-categories#124]
Problem 1
    - Root composer.json requires rinvex/laravel-categories ^6.1 -> satisfiable by rinvex/laravel-categories[v6.1.0].
    - rinvex/laravel-categories v6.1.0 requires spatie/laravel-translatable ^5.2.0 -> found spatie/laravel-translatable[5.2.0, v5.x-dev] but it conflicts with your root composer.json require (^6.0).

**Comment by Omranic** [comment]
Please make sure you have the minimum required version of PHP v8 and Laravel v9
