### ISSUE TITLE
Laravel 9

### ISSUE THREAD

**Issue by volkankaban** [rinvex/laravel-categories#125]
Such a shame old projects can't move to Laravel 9 due to waiting for updates!

**Comment by Omranic** [comment]
@volkankaban not sure which old project you're referring to!

This package already compatible with both Laravel v9 & v10 too!
https://github.com/rinvex/laravel-categories/blob/master/composer.json#L43-L52

If you've a problem using this package, please post a meaningful report with what issue you're facing, so we can help you.
