### ISSUE TITLE
Composer update

### ISSUE THREAD

**Issue by colivinggit** [rinvex/laravel-categories#126]
Hi,
Any chance to update it so it works with spatie translatable 6?

**Comment by Omranic** [comment]
Yeah sure, thanks for the heads-up. Will do that and update you here

**Comment by PitchRE** [comment]
Looking forward for it  :smiley_cat:

**Comment by Omranic** [comment]
Fixed here and new version released, thanks for your patience https://github.com/rinvex/laravel-categories/commit/3b7f2c64059f7b3985467bde99feb66b8f32be6b
