### ISSUE TITLE
Unable to composer require package due to requiring illuminate/support ^5.5|^6.0|^7.0|^8.0

### ISSUE THREAD

**Issue by syahnur197** [rinvex/laravel-categories#128]
![image](https://user-images.githubusercontent.com/18722385/176803492-1466dc71-c449-40ad-84dc-60eedd4d3f0c.png)

Steps to reproduce:
1. Install Laravel with sail
2. Develop within VsCode Devcontainer
3. Install Laravel Breeze (in Devcontainer)
4. Install this package (in Devcontainer)

**Comment by Omranic** [comment]
## Note for Laravel v9

This package requires `felixkiss/uniquewith-validator` dependency, which is not yet compatible with Laravel v9! However as a temporary workaround, add [Laravel Shift](https://github.com/felixkiss/uniquewith-validator/pull/131)'s fork to the `repositories` property of your project root `composer.json`:
```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/uniquewith-validator.git"
        }
    ]
}
```

https://github.com/rinvex/laravel-support#note-for-laravel-v9

**Comment by bistory** [comment]
@Omranic unfortunately, it seems that the author of uniquewith-validator abandoned his package, he is not merging PR he received about this compatibility issue...

**Comment by mattvb91** [comment]
@bistory I have a PR request here to fix this issue: https://github.com/rinvex/laravel-support/pull/66 hopefully it will get merged soon

**Comment by Omranic** [comment]
@bistory @mattvb91 In the time being, please follow the instructions here in order to make it work without issues https://github.com/rinvex/laravel-support#note-for-laravel-v9

**Comment by Omranic** [comment]
Update: we dropped the `felixkiss/uniquewith-validator` dependency 🙂 https://github.com/rinvex/laravel-support/commit/2bf69b8dcbf6f18ecd97c2c7b43ae441d58765cd

**Comment by mattvb91** [comment]
thank you @Omranic
