### ISSUE TITLE
Installation problem in ubuntu 20.04

### ISSUE THREAD

**Issue by muhammedkamal** [rinvex/laravel-categories#129]
when using `composer require rinvex/laravel-categories`
I get the following error 

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - felixkiss/uniquewith-validator 3.4.2 requires illuminate/support ^5.5|^6.0|^7.0|^8.0 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - rinvex/laravel-support[v6.1.0, ..., v6.1.1] require felixkiss/uniquewith-validator dev-l9-compatibility -> found felixkiss/uniquewith-validator[dev-master, 1.0.0, ..., 1.1.4, 2.0.0, ..., 2.0.8, 3.0.0, ..., 3.4.2] but it does not match the constraint.
    - rinvex/laravel-categories v6.1.1 requires rinvex/laravel-support ^6.0.0 -> satisfiable by rinvex/laravel-support[v6.0.0, ..., v6.1.1].
    - rinvex/laravel-support[v6.0.0, ..., v6.0.3] require felixkiss/uniquewith-validator ^3.4.2 -> satisfiable by felixkiss/uniquewith-validator[3.4.2].
    - Root composer.json requires rinvex/laravel-categories ^6.1.1 -> satisfiable by rinvex/laravel-categories[v6.1.1].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
`
I have the following lines in my composer.json file 
` "minimum-stability": "dev",
    "prefer-stable": true`
    
I am using PHP 8.1.7 along with laravel 9

**Comment by Omranic** [comment]
## Note for Laravel v9

This package requires `felixkiss/uniquewith-validator` dependency, which is not yet compatible with Laravel v9! However as a temporary workaround, add [Laravel Shift](https://github.com/felixkiss/uniquewith-validator/pull/131)'s fork to the `repositories` property of your project root `composer.json`:
```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/uniquewith-validator.git"
        }
    ]
}
```

https://github.com/rinvex/laravel-support#note-for-laravel-v9

**Comment by Omranic** [comment]
Update: we dropped the `felixkiss/uniquewith-validator` dependency 🙂 https://github.com/rinvex/laravel-support/commit/2bf69b8dcbf6f18ecd97c2c7b43ae441d58765cd
