### ISSUE TITLE
for laravel 9 and php 8.1 i had error at install

### ISSUE THREAD

**Issue by mohammad-salehealizadegan** [rinvex/laravel-categories#131]
Problem 1
    - rinvex/laravel-categories[v6.1.0, ..., v6.1.2] require rinvex/laravel-support ^6.0.0 -> satisfiable by rinvex/laravel-support[v6.0.0, ..., v6.1.3].
    - rinvex/laravel-support[v6.0.0, ..., v6.0.3] require felixkiss/uniquewith-validator ^3.4.2 -> satisfiable by felixkiss/uniquewith-validator[3.4.2].
    - felixkiss/uniquewith-validator 3.4.2 requires illuminate/support ^5.5|^6.0|^7.0|^8.0 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - rinvex/laravel-support[v6.1.0, ..., v6.1.3] require felixkiss/uniquewith-validator dev-l9-compatibility -> found felixkiss/uniquewith-validator[dev-master, 1.0.0, ..., 1.1.4, 2.0.0, ..., 2.0.8, 3.0.0, ..., 3.4.2] but it does not match the constraint.
    - Root composer.json requires rinvex/laravel-categories ^6.1 -> satisfiable by rinvex/laravel-categories[v6.1.0, v6.1.1, v6.1.2].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require rinvex/laravel-categories:*" to figure out if any version is installable, or "composer require rinvex/laravel-categories:^2.1" if you know which you need.

**Comment by mohammad-salehealizadegan** [comment]
I found my answer in the previous issue's comments
thank you

**Comment by Omranic** [comment]
@mohammad-salehealizadegan great, glad you found your way.

For reference if anyone else having the same issue, please check these instructions
https://github.com/rinvex/laravel-support#note-for-laravel-v9

## Note when using this package with Laravel v9

This package requires `felixkiss/uniquewith-validator` dependency, which is not yet compatible with Laravel v9! However as a temporary workaround, add [Laravel Shift](https://github.com/felixkiss/uniquewith-validator/pull/131)'s fork to the `repositories` property of your project root `composer.json`:
```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/uniquewith-validator.git"
        }
    ]
}
```

**Comment by Omranic** [comment]
Update: we dropped the `felixkiss/uniquewith-validator` dependency 🙂 https://github.com/rinvex/laravel-support/commit/2bf69b8dcbf6f18ecd97c2c7b43ae441d58765cd
