### ISSUE TITLE
attach, sync working only with children where parent id is 1 

### ISSUE THREAD

**Issue by muhammedkamal** [rinvex/laravel-categories#132]
I am trying to sync some sub-categories to my user I am able to do this 
`$engineer->syncCategories(
                     request->input('sub_categories') ,true
                    );`
with categories where parent id is 1 but with all other categories I can not do such what is the problem

**Comment by Omranic** [comment]
@muhammedkamal I'm not sure I understand your issue, if this is still exists, kindly explain with more details. Thanks
