### ISSUE TITLE
Get all products from categories

### ISSUE THREAD

**Issue by rlidev** [rinvex/laravel-categories#134]
I am creating an autocomplete that shows the categories, I would like to bring all the products related to the category. The problem is that I can only find the products to the assigned category but it does not bring me the products if it is a parent category, I understand that it is my code that is wrong.

For example, the gaming category (parent) shows 0 products, and the playstation category (child) shows 1 product, can someone help me solve this?

**Parent category 'gaming' 0 product**
![Screenshot_9](https://user-images.githubusercontent.com/560115/216186680-e90bfc2e-ae2d-4dfe-b572-4bb8c9ef04f7.png)

**Child category 'playstation' 1 product**
![Screenshot_8](https://user-images.githubusercontent.com/560115/216186261-b8e66316-b770-4d3e-b85d-4dc522c8f2a4.png)

**Controller**
![Screenshot_6](https://user-images.githubusercontent.com/560115/216186274-229c2cad-57c5-444d-864a-7e50ba074776.png)

**Model**
![Screenshot_7](https://user-images.githubusercontent.com/560115/216186295-4db50d40-a939-4de6-ad30-cbf09e84b6b7.png)

What I need is that you bring me the products of the category and their descendants, thanks.

**Comment by Omranic** [comment]
This might be within the scope of the parent package https://github.com/lazychaser/laravel-nestedset
