### ISSUE TITLE
Can't install in Laravel 10 project

### ISSUE THREAD

**Issue by darkons** [rinvex/laravel-categories#136]
I just upgraded my current project to Laravel 10 successfully except this package. Apparently, the problem is in the **watson/validating** dependency of **rinvex/laravel-support**.
Currently it depends on **watson/validating:7.0.0** which is not compatible with Laravel 10. The version that should be used is 8.0.0

https://github.com/dwightwatson/validating/blob/8.0.0/composer.json

**Edit:** I have just seen  the new PR's in **laravel-support** repository.

**Comment by darkons** [comment]
Please, it would be great if **laravel-support** PR's could be merge as soon as possible. Upgraded projects to Laravel 10 do not work with this package.

**Comment by MirazMac** [comment]
Any updates?

**Comment by rlidev** [comment]
+1

**Comment by MirazMac** [comment]
Is this abandoned?

**Comment by batv45** [comment]
+1

**Comment by Omranic** [comment]
@rlidev @darkons @MirazMac @batv45 fixed in latest release https://github.com/rinvex/laravel-categories/commit/0790a7a4e05fd975f7e63558297ea5f369f6ebdc
