### ISSUE TITLE
Is there a way to associate two parents and filter the children's for each child? 

### ISSUE THREAD

**Issue by seche** [rinvex/laravel-categories#137]
Looking for a way to manage category associations where **Parent 1** is associated with **Parent 2**. Then from there each children of **Parent 1** would be associated to all or a selected set of children from **Parent 2**. Essentially creating a relationship between parents and assigning sets of values for each child? 

Goal is to make a filtered list form a parent/child selection.

Would this be out of scope?

**Comment by Omranic** [comment]
This might be within the scope of the parent package https://github.com/lazychaser/laravel-nestedset
