### ISSUE TITLE
[Proposal] Add isFirst() and isLast()

### ISSUE THREAD

**Issue by ivanBell199** [rinvex/laravel-categories#143]
Thank you for this great package. I have just started using it and it is very enjoyable. Unless I overlooked, it seems there are no methods to check if a node is first/last within its level. I think it would be useful for something like disabling "up" and "down" buttons when reordering is needed. In my project I simply adjusted methods `up()` and `down()`:

```
    /**
     * Check if node is first among siblings.
     *
     * @return bool
     */
    public function isFirst()
    {
        $sibling = $this->prevSiblings()
            ->defaultOrder('desc')
            ->first();

        return $sibling ? false : true;
    }

    /**
     * Check if node is last among siblings.
     *
     * @return bool
     */
    public function isLast()
    {
        $sibling = $this->nextSiblings()
            ->defaultOrder()
            ->first();

            return $sibling ? false : true;
    }
```

Do you think it is worth being added to the package?

**Comment by Omranic** [comment]
Hey @ivanBell199, thanks for the good question and sorry for the late reply.

For that use case, I'd rely on the core package https://github.com/lazychaser/laravel-nestedset

### Checking if a node is the first in its level

To check if a node is the first in its level, you can compare its `lft` value with the `lft` values of its siblings. A node is the first in its level if its `lft` value is the smallest among its siblings.

Here's an example:

```php
use App\Models\Category; // Replace with your actual model namespace

// Assume $node is the node you want to check
$node = Category::find($nodeId);

$isFirst = $node->siblings()->where('lft', '<', $node->lft)->doesntExist();
```

Similarly, to check if a node is the last in its level, you can compare its `lft` value with the `lft` values of its siblings. A node is the last in its level if its `lft` value is the largest among its siblings.

### Explanation

- `$node->siblings()` returns a query builder for all sibling nodes.
- `where('lft', '<', $node->lft)` checks for siblings with a lower `lft` value.
- `where('lft', '>', $node->lft)` checks for siblings with a higher `lft` value.
- `doesntExist()` checks if any records match the query.

I haven't tested it, but this approach is supposed to ensure that you correctly identify whether a node is the first or last in its level within the nested set hierarchy.
