### ISSUE TITLE
How to override automatic migration

### ISSUE THREAD

**Issue by zcwilt** [rinvex/laravel-categories#16]
The migration for the categories/categorizables tables is run automatically from the service provider boot method, with no way to disable this. 

I need to add some extra fields to the categories tables.

The only real way I can do this at the moment is to create a new migration with a different table name, and change the config settings.

**Comment by zcwilt** [comment]
Maybe we can fix this using a config setting. 

e.g

        $runMigration = config('rinvex.categories.automatic-migration', true);
        if ($this->app->runningInConsole() && $runMigration) {
            $this->loadMigrationsFrom(__DIR__.'/../../database/migrations');
        }

in the boot method.

**Comment by zcwilt** [comment]
BTW
Another workaround I'm using is to update the schema in a seeder e.g. 

        Schema::table('categories', function (Blueprint $table) {
            $table->boolean('visible')->default(1);
        });

However still feel some way of disabling the automatic migration would be useful.

Can do a PR if you want.

**Comment by Omranic** [comment]
If you want to add new fields to the categories table you've to create another migration that just alter the table (with the same table name). You don't have to change the table name or anything else, just add a new migration and add/change whatever columns you need.

I don't see a real value on disabling this, nor even a real limitation on keeping it the same way. We ourselves do exactly as you said without any issues, see the [cortex/categories](https://github.com/rinvex/cortex-categories/tree/develop/database/migrations) module which depends on this package, and alter the tables as needed.

**Comment by zcwilt** [comment]
Hi,

yes you are of course correct. 
My problem was that i had installed the nested set stuff some time ago, and created a migration for the categories table. When I updated to use your code that migration was still there with a really old timestamp and was running `before` your migration. Dropping my old migration and creating a new one just to do the alter table works fine,

**Comment by Omranic** [comment]
Oh, thanks for your followup.
Actually that last comment make sense, I may have to rethink the auto-migration based on your situation, where there's already similar tables existing before our package installation. Good point, to be considered 👌

**Comment by MannikJ** [comment]
What is the progress on this? Why is there even any strife about adding the option to deactivate automatic migrations? In my opinion this is a must have. Otherwise conflicts are inevitable.

And I am too stupid to publish the migration files to change them. How can I do that?

**Comment by Omranic** [comment]
All packages have been updated to include this feature, check latest releases 😉 enjoy!
