### ISSUE TITLE
Error on attaching category by slug

### ISSUE THREAD

**Issue by zcwilt** [rinvex/laravel-categories#17]
In the documentation it says

    // Single category slug
     $post->attachCategories('test-category');

However this generates an error `Invalid argument supplied for foreach()`

doing `$post->attachCategories(['test-category']);` works.

**Comment by zcwilt** [comment]
So think I have found the problem in `function prepareCategoryIds($categories)`

        if (is_string($categories) || (is_array($categories) && is_string(array_first($categories)))) {
            $categories = app('rinvex.categories.category')->whereIn('slug', $categories)->get()->pluck('id');
        }

The problem is that if $categories is a string it is passed unchanged to the whereIn clause, which expects an array.

**Comment by zcwilt** [comment]
I can try and do a PR if that's ok.

**Comment by bzx** [comment]
I also had a problem inserting categories using an array of IDs... whereas using array of slugs works fine... :(

**Comment by Omranic** [comment]
@zcwilt Thank you for this catch and sorry for the -long- delay noticing this issue.
Fixed in recent commit https://github.com/rinvex/laravel-categories/commit/c25d97d29622dd6ddb455ed39cfbbe6b764dfd97

**Comment by Omranic** [comment]
@bzx thank you for your patience, this has been fixed in recent commit too https://github.com/rinvex/laravel-categories/commit/8ca17e72ed7849a9d38a5aecda954c3a81cc2938
