### ISSUE TITLE
Soft deletes

### ISSUE THREAD

**Issue by ghost** [rinvex/laravel-categories#25]
The documentation says about soft delete being supported, but the Category model doesn't use the SoftDeletes trait. Am i missing something trying to make my categories soft deletable?

**Comment by mostafaznv** [comment]
just create category model in `app` directory and extend Rinvex Category `model`.
so you can add SoftDelete trait 

don't forget to change category model in config file

**Comment by ghost** [comment]
Thanks!

**Comment by giovannipds** [comment]
@mostafaznv why is that not suggested on README? #58

**Comment by giovannipds** [comment]
**Be careful using what @mostafaznv proposed**!

I was using it and apparenly laravel-categories uses a package called laravel-cacheable, which running these (apparently same method) returned different and not synced results:
```php
Category::find(1) // serving me old cached data

app('rinvex.categories.category')->find(1) // working good
```

**Comment by giovannipds** [comment]
Just get it. If you're gonna use this approach, just remember to set `$cacheLifetime` for having control of cache issues.

If you don't want to use the cache system by default, just use this on your extended model:
```php
protected $cacheLifetime = 0;
```

**Comment by Omranic** [comment]
I'm thinking about dropping laravel-cacheable dependency and leave it optional to developers to use it or implement any other caching strategies on their application layer. I believe this is not required on the core vendor packages level. Let me know if you've any thoughts about that..

**Comment by mostafaznv** [comment]
> I'm thinking about dropping laravel-cacheable dependency and leave it optional to developers to use it or implement any other caching strategies on their application layer. I believe this is not required on the core vendor packages level. Let me know if you've any thoughts about that..

I think cache is required for this package.
But what's annoying about it is that sometimes we need more flexibility.
I mean it's better to have an option to disable/enable cache, or have an option to cache custom queries or ...

I think your cache layer is cool, but it need some features and improvements

**Comment by Omranic** [comment]
I'm open to any improvement suggestions and PRs 😉

**Comment by Omranic** [comment]
Thank you for the valuable input and discussion, caching has been dropped from the core package for more flexibility. It make more sense to move that responsibility to the application layer. Check recent commit c33ec2d but anyone can still utilize the same (or different) caching strategies.

A new release should be tagged soon! Happy coding 🙂

**Comment by Omranic** [comment]
Commenting on SoftDeletes I believe it makes more sense to move this responsibility to the application layer, so I removed that phrase from Readme to keep it flexible for everyone, and reduce confusion https://github.com/rinvex/laravel-categories/commit/3715294920950afc1cbd9bdf80480e82ff43355d
