### ISSUE TITLE
Order by name

### ISSUE THREAD

**Issue by ghost** [rinvex/laravel-categories#26]
I'm trying to order categories by name. Is possible?

I have tried:

```php
$categories = app('rinvex.categories.category')->orderBy('name')->get();
// or
$categories = app('rinvex.categories.category')->get()->sortBy('name');
```

**Comment by zcwilt** [comment]
hmm.

I just tried this in a test route 

        $categories = app('rinvex.categories.category')->orderBy('name', 'DESC')->get();
        $names = $categories->pluck('name');
        dump($names->toArray());

and ordering worked fine.

How are you seeding your categories.

My test seeder looks like 

        $root1 = app('rinvex.categories.category')->create([
            'name' => ['en' => 'product-root'],
            'description' => ['en' => 'product-root']
        ]);

        $root2 = app('rinvex.categories.category')->create([
            'name' => ['en' => 'other-root'],
            'description' => ['en' => 'other-root']
        ]);


        $node1 = app('rinvex.categories.category')->create([
            'name' => ['en' => 'x'],
            'description' => ['en' => '[EN]Category One']
        ], $root1);
        $node2 = app('rinvex.categories.category')->create([
            'name' => ['en' => 'y'],
            'description' => ['en' => '[EN]Category Two']
        ], $root1);
        $node2_1 = app('rinvex.categories.category')->create([
            'name' => ['en' => 'z'],
            'description' => ['en' => '[EN]Category Two Sub 1']
        ], $node2);

        app('rinvex.categories.category')->create([
            'name' => ['en' => 'q'],
            'description' => ['en' => '[EN]other One']
        ], $root2);

**Comment by ghost** [comment]
Seems to be working now. I don't remember what happened that it was not working. 

I appreciate your response.
