### ISSUE TITLE
Possibly a bug

### ISSUE THREAD

**Issue by ghost** [rinvex/laravel-categories#28]
Here follows the behavior:

1. I have a Product model that is using the Categorizable trait.
2. This Product model also uses the SoftDeletes trait.
3. A product is registered with some categories attached.
4. When i run the "destroy" method from the model to soft deletes it, all categories are detached.

I was just expecting to disable the registry and keep your categories.

**Comment by Omranic** [comment]
Well, this isn’t tested scenario, but it could be valid since we still didn’t implement or test SoftDelete behavior, but it’s planned since the beginning. For now, please try to change current behavior I’m your own model, until this is ready. Sorry for the inconvenience..

**Comment by ghost** [comment]
No problem, let me know if you need any help with this.

Cheers.

**Comment by Omranic** [comment]
Any PRs are always welcome of course 🙏😁

**Comment by ghost** [comment]
Haha ok, i made a PR. I'm waiting for this to be merged into master branch. Thank you.

**Comment by darkons** [comment]
Could this fix be applied to the 6.0.0 version for Laravel 8.x users?

**Comment by Omranic** [comment]
@darkons thank you for your message. Currently we're not supporting older versions of Laravel, however you can fork it and apply the same fix if you want.
