### ISSUE TITLE
json type migration

### ISSUE THREAD

**Issue by zemenik** [rinvex/laravel-categories#30]
the jsonable() in migrations file create a json type field in mysql
that's ok. but older version of mariadb not support json type.
i install CWP on centos . it default database was mariadb.
so i had to remove jsonable() from migrations and migrate my database.
my app work fine.
i suggest you, if it's unnecessary remove it from migrations.

**Comment by Omranic** [comment]
There was few enhancements recently to this particular feature, but the package is not tested on mariadb. You're welcome to send PR for this if you believe it would be helpful for others :)
