### ISSUE TITLE
Laravel 5.7 Support

### ISSUE THREAD

**Issue by DiyanDev** [rinvex/laravel-categories#31]
Hello, I tried to install the package on Laravel 5.7.2 and I am getting:

`don't install illuminate/validation 5.6.x-dev|don't install laravel/framework v5.7.2`

Are you going to add 5.7 support anytime soon? 

-Thank you.

**Comment by aalaap** [comment]
@DiyanDesigns This appears to work just fine with 5.7.13. Are you sure this isn't caused by any other conflicting packages?

**Comment by DiyanDev** [comment]
Yea the commit on 22 of September  (8b7eed5be70becd8005a0d773938ab9343c9b60b) added support for 5.7, this issue can be closed now.
