### ISSUE TITLE
prepareCategoriesIds issue with request as string

### ISSUE THREAD

**Issue by andreakru** [rinvex/laravel-categories#34]
The method prepareCategoryIds() failed if you pass categories IDs as string, this happen when come from request.

I think that you could enhance below code by checking if is not an integer, by converting to int.

Current code:

```

        // Find categories by slug, and get their IDs
        if (is_string($categories) || (is_array($categories) && is_string(array_first($categories)))) {
            $categories = app('rinvex.categories.category')->whereIn('slug', $categories)->get()->pluck('id');
        }
```

Something like:

```

        // Find categories by slug, and get their IDs
        if (is_string($categories) || (is_array($categories) &&  (int) $array[0] === 0 )) {
            $categories = app('rinvex.categories.category')->whereIn('slug', $categories)->get()->pluck('id');
        }
```

Means that if first element of array converted to int return 0, is a string.

**Comment by Omranic** [comment]
@macagoraga thank you for your patience, this has been fixed in recent commit https://github.com/rinvex/laravel-categories/commit/8ca17e72ed7849a9d38a5aecda954c3a81cc2938
