### ISSUE TITLE
Get categories translation

### ISSUE THREAD

**Issue by lemonjp** [rinvex/laravel-categories#35]
Hi there,

Is there any function get categories translation?

like this.

    $categories = app('rinvex.categories.category')->get()->toTree();
    $categories = $categgories->getTranslation('name', 'ja');

instead of that I've managed to get like this.

    $categories = app('rinvex.categories.category')->get()->toTree();
    $traverse = function ($categories) use (&$traverse, $request) {
        foreach ($categories as $category) {
            $category->name = $category->getTranslation('name', 'ja');
            $traverse($category->children);
        }
    };

    $traverse($categories);

is that the correct solution?

**Comment by Omranic** [comment]
This package utilize https://github.com/spatie/laravel-translatable so you may need to check that dependency package for more details. Whatever supported there, is supported here 😉
