### ISSUE TITLE
laravel-transable 2.1 not supported by laravel 5.7

### ISSUE THREAD

**Issue by nagi1** [rinvex/laravel-categories#39]
In your composer.json file you require spatie/laravel-transable ^2.1.0 which is not supported by laravel 5.7 and give me this error :(

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install spatie/laravel-translatable 2.2.1
    - Installation request for rinvex/laravel-categories ^1.0 -> satisfiable by rinvex/laravel-categories[v1.0.0].
    - Conclusion: remove laravel/framework v5.7.13
    - Installation request for spatie/laravel-translatable (locked at 3.0.1) -> satisfiable by spatie/laravel-translatable[3.0.1].
    - Conclusion: don't install laravel/framework v5.7.13
    - rinvex/laravel-categories v1.0.0 requires spatie/laravel-translatable ^2.1.0 -> satisfiable by spatie/laravel-translatable[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.2.0, 2.2.1].`

Update your composer.json to support spatie/laravel-translatable 3.0

**Comment by Omranic** [comment]
Fixed in latest release :) enjoy
