### ISSUE TITLE
Add category with translations different than the app current locale.

### ISSUE THREAD

**Issue by NassarX** [rinvex/laravel-categories#4]
Can't add category with translations that different than the **app current locale** .

`        

        // current locale = ar
        Category::create([
            'slug' => 'custom-category-slug-1',
            'name' => ['en' => 'name in english', 'de' => 'name in germany']
        ]);
`
it only works when adding additional translation with same **app current locale**.

I don't know if that related to [spatie translatable](https://github.com/spatie/laravel-translatable) package

**Comment by Omranic** [comment]
Tested & it works like a charm. This issue should be fixed in latest releases of this package. Please feel free to reopen this issue or a new one if you need further assistance 🙂
