### ISSUE TITLE
Get tree without children in root

### ISSUE THREAD

**Issue by chadidi** [rinvex/laravel-categories#41]
I need to get a tree like this

```
root
  child
  child
    child
root
 child
```
I am using this `app('rinvex.categories.category')->get()->toTree();` and this is the result:
```
root
  child
  child
    child
child
child
child
root
 child
child
```

Thanks

**Comment by zcwilt** [comment]
try 
app('rinvex.categories.category')->whereNotNull('parent_id')->get()->toTree();

**Comment by Omranic** [comment]
These children that don't have roots means they don't have parent category, which means they're now considered roots / parents themselves. You may need to check the core package that we've built this one upon, to understand how to deal with parents and children https://github.com/lazychaser/laravel-nestedset
