### ISSUE TITLE
Category model doesn't considered as having relationship

### ISSUE THREAD

**Issue by cosfat** [rinvex/laravel-categories#43]
I use [Kyslik/column-sortable](https://github.com/Kyslik/column-sortable) for handling column sorting in Laravel 5.[5-7].

But the issue here is your Category model doesn't considered as having relationship like hasOne or belongsTo.

Of course I have added these functions to my Models in order to work-around the problem but the fact is, it only hides the try/catch errors. No functionality at all.

**Comment by mostafaznv** [comment]
I think packages is using cached categories and you will get null (or a hardcoded relation model)

**Comment by Omranic** [comment]
I'm not sure about the above package, but our categories package is working fine with https://github.com/spatie/eloquent-sortable

If you believe there's something we can improve in this package, feel free to submit a PR 😉
