### ISSUE TITLE
Error dispatcher fire on creation of model

### ISSUE THREAD

**Issue by sascha-schieferdecker** [rinvex/laravel-categories#46]
Using Laravel 5.8.2, new to Laravel. Unsure if it's a bug or I am using it incorrectly. Glad for any help.

When creating a new model in the controller:

```
$category = app('rinvex.categories.category')->fill(['name' => $request->name, 'description' => $request->description]);
$category->save();
```

an exception is thrown:

Call to undefined method Illuminate\Events\Dispatcher::fire()

`vendor/rinvex/laravel-cacheable/src/CacheableEloquent.php`

From line 212:

```
           return true;
        }
 
        // We will append the names of the class to the event to distinguish it from
        // other model events that are fired, allowing us to listen on each model
        // event set individually instead of catching event for all the models.
        $event = "eloquent.{$event}: ".static::class;
 
        $method = $halt ? 'until' : 'fire';
 
        return static::$dispatcher->{$method}($event, static::class);
    }
 
    /**
     * Reset cached model to its defaults.
     *
     * @return $this
     */
    public function resetCacheConfig()
    {
        ! $this->cacheDriver || $this->cacheDriver = null;
        ! $this->cacheLifetime || $this->cacheLifetime = -1;
 
        return $this;
    }

```

**Comment by dom235** [comment]
Stay calm, it's a bug and if we pay a little more patience it's getting fixed soon i think. I need this fix too

The "fire" method has been deprecated

https://github.com/laravel/framework/pull/26392

**Comment by Omranic** [comment]
Fixed and stable release has been tagged already, enjoy 😉 https://github.com/rinvex/laravel-cacheable/releases/tag/v2.0.1
