### ISSUE TITLE
Dependency Bug In New Release v2.1.0

### ISSUE THREAD

**Issue by MannikJ** [rinvex/laravel-categories#52]
I you have already used this package or `rinvex/laravel-support` before and then upgraded to v 2.1.0 there will be errors, because ConsoleTools does not exist.
The `rinvex/laravel-support` dependency in composer.json should be bumped to `^2.1.0` to ensure the required ConsoleTools trait exists.

**Comment by Omranic** [comment]
We don't have to do so, you may need to check what does the **caret** means in [composer version constrains](https://getcomposer.org/doc/articles/versions.md#caret-version-range-).

I tell you why you get the old version, two possible reasons:

1. Probably one of the packages you're installing requires older version of a dependency, that v2.1.0 no longer supports, so composer automatically tries to solve the problem by lowering the version of the conflicting package, so all packages can agree on dependency versions. You can fix this by checking your custom packages, that's one way to do it, there's other ways too.

2. Sometimes it's composer cache issue (rare issue), but you can fix it by running this command `composer clear-cache`, then re-install

**Comment by MannikJ** [comment]
I won't exclude I am really getting something wrong here, but I also think you did not understand my point. 

From the latest release on `rinvex/laravel-categories` in fact needs a version of `rinvex/laravel-support` greater than or equal to v2.1.0, because these are the only versions that contain the ConsoleTools trait. 

However, v2.0.0 for example would also meet the requirement specified in package.json (^2.0.0). 
So if for some reason a version of `rinvex/laravel-support` that matches ^2.0.0 has been installed before, composer won't do anything to get a later version unless you tell it to.

I did not say v2.1.0 does not match ^2.0.0. There will be no problem if you just install it from scratch or update the support package explicitly. You do not _not get_ the new version, composer just leaves it as it is.

**Comment by Omranic** [comment]
I always prefer explicit definitions, so I updated all packages now to require ^2.1.0, enjoy ;)

But responding to your point, I don't believe what you've said is correct. Composer should pull the newest matched version, and I do understand your point. As I said, the behavior you're getting could be caused by one of the two reasons I mentioned above.

**Comment by MannikJ** [comment]
Maybe we are both correct. I can just say that I encountered the issue for whatever reason. And from my point of view, specifying it as ^2.1.0 is the only way that really makes sense. So thank you for helping my inner Monk ;)
I also still don't understand why composer should even try to update a package automatically if there is already a matching version installed. I will keep a closer look on what it actually does in the future...
