### ISSUE TITLE
Nova Package

### ISSUE THREAD

**Issue by shazibrazzaq** [rinvex/laravel-categories#53]
Hey guys,

Do you have any nova package available for this categorisable trait and tree view?

**Comment by solarsoft0** [comment]
https://github.com/koss-shtukert/laravel-nova-select2-auto-complete this package is compatible with laravel-categories

**Comment by solarsoft0** [comment]
but not the tree view

**Comment by coccoinomane** [comment]
Hi there! First of all thank you for taking the time to develop this great package!
I too was wondering if there was a way to assign categories to a model from within the interface of Laravel Nova. 
Thank you,
Guido

**Comment by Omranic** [comment]
Currently we don't have Nova package for this feature, but feel free to suggest any updates that may make it easier for you. PRs always welcome. Also check @solarsoft0 suggestion above, may be what you're looking for..

**Comment by coccoinomane** [comment]
Thank you @Omranic!
The package suggested by @solarsoft0 is grrat to show the main category, but  not nested ones.
Maybe in the future I will consider doing a PR, thank you anyway!
Cheers,
Guido
