### ISSUE TITLE
Laravel sluggable Arabic / UTF problem

### ISSUE THREAD

**Issue by AO-IO** [rinvex/laravel-categories#56]
I want to disable the translation of a slug.

for example. my locale is Arabic:

let's say the name is: هاندس

the slug should be هاندس not hands.

how I can make this work?

I searched in Laravel Sluggable docs but I find nothing helpful.

**Comment by AO-IO** [comment]
Solution 💯  👍 :

by using this package https://github.com/cocur/slugify.

go to `HasSlug` Trait in `vendor/spatie/laravel-sluggable`

at the top use `use Cocur\Slugify\Slugify;`

override the method `generateNonUniqueSlug()`

```PHP
   protected function generateNonUniqueSlug(): string
    {
        $slugField = $this->slugOptions->slugField;
        if ($this->hasCustomSlugBeenUsed() && ! empty($this->$slugField)) {
            return $this->$slugField;
        }

        $slugify = new Slugify(['rulesets' => ['default', 'arabic']]);

        return $slugify->slugify($this->getSlugSourceString(), $this->slugOptions->slugSeparator);
    }
```
Voila!

**Comment by Omranic** [comment]
This package depends on `spatie/laravel-sluggable` but I'm grald you made it work for your project. Happy coding.. :)
