### ISSUE TITLE
Why not suggesting to create and use an app's own Category model?

### ISSUE THREAD

**Issue by giovannipds** [rinvex/laravel-categories#58]
Hi!
Being this possible, why don't we suggest it on readme?

```sh
php artisan make:model Category
```

**app/Category.php:**
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Rinvex\Categories\Models\Category as RinvexCategory;

class Category extends RinvexCategory
{
    //
}
```
Isn't it better than having to write `app('rinvex.categories.category')` over and over again?

Waiting to hearing from you. Thanks!

**Comment by Omranic** [comment]
We prefer to always use `app('rinvex.categories.category')` instead of calling a hardcoded model namespace, and the reason why is to give developers the flexibility to override models at any point of runtime in the IoC container, and still be able to get the newly overridden model without having to change one line of your code.

This decision has been made as we design the modular architecture of our project [`rinvex/cortex`](https://github.com/rinvex/cortex) where new modules are allowed to be installed, and modify project behavior.

Feel free to re-open for discussion if having any other thoughts 🙂

**Comment by giovannipds** [comment]
@Omranic hi! I'm glad you've replied! Thank you for explaining the reasons.

Just another question: is that mandatory? Isn't safe to extend it on our own models?

Got a case where using `Category::find(1)` served me old  cached data while `app('rinvex.categories.category')->find(1)` worked normally, I don't if this happens because of `laravel-cacheable` dependency or what.

Thank you!

**Comment by giovannipds** [comment]
Running `php artisan cache:clear` solved the case.

**Comment by giovannipds** [comment]
Hi again. Don't worry, just got it!

I've taken a look at [laravel-cacheable](https://github.com/rinvex/laravel-cacheable). Just set `$cacheLifetime` on my extended model and it all goes as expected now. Thank you again!

**Comment by Omranic** [comment]
I'm thinking about dropping laravel-cacheable dependency and leave it optional to developers to use it or implement any other caching strategies on their application layer. I believe this is not required on the core vendor packages level. Let me know if you've any thoughts about that..

**Comment by ingageco** [comment]
@Omranic that sounds like a good idea. the same happened to me as @giovannipds (i also am extending the model). Caching should be done independently in the project as the developer decides, IMO.

**Comment by giovannipds** [comment]
I agree with you guys @Omranic @ingageco, should be optional.

**Comment by Omranic** [comment]
Thank you for the valuable input and discussion, caching has been dropped from the core package for more flexibility. It make more sense to move that responsibility to the application layer. Check recent commit https://github.com/rinvex/laravel-categories/commit/c33ec2dcb5b99b7fcc18b28d3c5c1d1bc224b286

A new release should be tagged soon! Happy coding 🙂
