### ISSUE TITLE
Is it possible to make slug translatable?

### ISSUE THREAD

**Issue by tmoldri** [rinvex/laravel-categories#59]
The main idea is in the title. I am creating an app where categories are retrieved by slug and the slug is also translatable.

**Comment by Omranic** [comment]
The whole idea behind slug is to be unique human readable identifier regardless of the content or language. So I believe your use case may be very specific for your project, in such case you can fork the package and do the changes you need 🙂

**Comment by tmoldri** [comment]
Okay, i will fork it and make the changes i need. I would just like to comment that in SEO standpoint, all slugs (urls) should be also in different languages. I am a backend developer so i cant really comment on it but this is what SEO people told me. Maybe i misunderstood something?
