### ISSUE TITLE
CategorySaved not found after update/insert categories

### ISSUE THREAD

**Issue by mostafaznv** [rinvex/laravel-categories#62]
I'm getting this error after saving categories.

> Class 'Rinvex\Categorys\Events\CategorySaved' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0)

I removed ```rinvex/laravel-categories``` and reinstalled it. but I saw error  everytime after insert/update.

Finally I solved that problem with adding this line to composer.json (```autoload.psr-4```)

> "Rinvex\\Categorys\\Events\\": "vendor/rinvex/laravel-categories/src/Events"

Please fix this problem in new versions.

Laravel version: 6.9
PHP versoin: 7.3 and 7.4
OS: ubuntu 18, centos 7

**Comment by mostafaznv** [comment]
and after doing this trick, I'm getting this log message in laravel.log files:

> Broadcasting [rinvex.categories.deleted] on channels [rinvex.categories.list] with payload:

what is it? I've never saw it before

**Comment by joooseb** [comment]
Same error here.
Laravel Version 6.0
PHP: 7.2
OS: Ubuntu 19.04

**Comment by joooseb** [comment]
I found the error, please check this PR:
https://github.com/rinvex/laravel-categories/pull/63

**Comment by Omranic** [comment]
Fixed in https://github.com/rinvex/laravel-categories/releases/tag/v3.0.4
