### ISSUE TITLE
syntax error, unexpected 'SlugOptions' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by ehsannowrouzi** [rinvex/laravel-categories#65]
Using laravel 6 and rinvex/laravel-categories version v3.0.4 i get an error when trying to access categories on a model
for example  : {{$products->categories}}

the error i get is :
syntax error, unexpected 'SlugOptions' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

when i update my php version to 7.4 the problem goes away , but for some reasons i don't want to upgrade my php version.
any idea?

**Comment by mbryne** [comment]
This is related to the bump minimum PHP version in laravel-sluggable: https://github.com/spatie/laravel-sluggable/issues/140

**Comment by Omranic** [comment]
> Pretty sure this is caused by a wrong PHP version being used. Make sure all web requests are handled by the right PHP version too
