### ISSUE TITLE
Add Order Column in Categorizable Table

### ISSUE THREAD

**Issue by humayunjavaid** [rinvex/laravel-categories#66]
Hi all

 i want to attach categories with order . how can i do that?
i have created order column in Categorizable  table .
 $service->attachCategories($category , [order => 1]);

Following is my Model

use Illuminate\Database\Eloquent\Model;
use Spatie\EloquentSortable\Sortable;
use Spatie\EloquentSortable\SortableTrait;
use Illuminate\Database\Eloquent\Relations\Pivot;

class Categorizable extends Pivot implements Sortable
{
    use SortableTrait;

    public $sortable = [
        'order_column_name' => 'order',
        'sort_when_creating' => true,
    ];

}

Regards

**Comment by Omranic** [comment]
Thank you @8humayun8 for your question.
This package don't and can't use sortable/ordereable features as it's built using **nested set model**, and depends on [lazychaser/laravel-nestedset](https://github.com/lazychaser/laravel-nestedset) which handles that logic internally. You need to understand how does it work first to be able to sort/order categories in their correct hierarchy. Check documentation here: https://github.com/rinvex/laravel-categories#manage-your-nodesnestedsets
