### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name

### ISSUE THREAD

**Issue by cryptocoinserver** [rinvex/laravel-categories#7]
I get this error:

`php artisan migrate --path="vendor/rin
vex/categorizable/database/migrations"

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table nam
  e '' (SQL: create table `` (`id` int unsigned not null auto_increment prima
  ry key, `slug` varchar(191) not null, `name` json not null, `description` j
  son null, `_lft` int unsigned not null default '0', `_rgt` int unsigned not
   null default '0', `parent_id` int unsigned null, `created_at` timestamp nu
  ll, `updated_at` timestamp null, `deleted_at` timestamp null) default chara
  cter set utf8mb4 collate utf8mb4_unicode_ci)

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table nam
  e ''

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table nam
  e ''
`
Do you know the reason for the empty table name?

THX

**Comment by cryptocoinserver** [comment]
I think the problem is that the migrations files can't get the table names defined in:
\vendor\rinvex\categorizable\config\config.php
`config('rinvex.categorizable.tables.categories')`

**Comment by cryptocoinserver** [comment]
I changed the names in the config.php 
Now its working. Strange....

**Comment by lakmalniranga** [comment]
Clear your config cache and re-run the migrations.
