### ISSUE TITLE
Typed property Rinvex\Categories\Models\Category::$slugOptions must be an instance of Spatie\Sluggable\SlugOptions, null used

### ISSUE THREAD

**Issue by dhi2** [rinvex/laravel-categories#70]
`Typed property Rinvex\Categories\Models\Category::$slugOptions must be an instance of Spatie\Sluggable\SlugOptions, null used
`

Release 4.0.0

PHP 7.4.3
Laravel 7

In Nova I am trying to create a resource:

```php
use Rinvex\Categories\Models\Category;

class Interest extends Resource
{
    public static $model = Category::class;

```

This only happens in Nova. It used to work and I've used it to create categories within Nova, this only started after upgrading PHP and Laravel.

**Comment by Omranic** [comment]
Hello, would you be able to advice how can we reproduce this issue, because when I tested this with Laravel v7.x I found it working smoothly without any issues. I don't use Nova, so if you can replicate it that would be great, also PRs are welcome :)

**Comment by dhi2** [comment]
I know it's _working smoothly without any issues_, as I said, it only happens in Nova and only started to happens in Nova after the upgrade. To reproduce it simply create a categories resource in Nova.

**Comment by dhi2** [comment]
I found the issue. I proposed the changes here: https://github.com/spatie/laravel-sluggable/compare/master...dhi2:patch-1

**Comment by dhi2** [comment]
I found another way to reproduce it without Nova:

```
$cats = app('rinvex.categories.category')->withDepth()
    ->having('depth', '<=', 1)
    ->defaultOrder()
    ->get();
```
But if you use `'1'` instead of `1` it'll won't throw the error.

**Comment by dhi2** [comment]
@Omranic The author is refusing to merge the pull request, he's wants more activity. Can you somehow add a fix or some workaround?

**Comment by Omranic** [comment]
Honestly I don't know what's the exact problem, if this issue is related to `rinvex/laravel-categories` then please provide steps on how to reproduce that issue on a native Laravel app, and I'll be glad to test it and see what we can do 🙂

**Comment by dhi2** [comment]
@Omranic I had already provided, see above.

**Comment by Omranic** [comment]
Please try again the recent release in `develop` branch as I tested your code above and it works without any issues. No errors, I was unable to reproduce your issue.
