### ISSUE TITLE
publish cannot work for laravel 6.*

### ISSUE THREAD

**Issue by seirralanzce** [rinvex/laravel-categories#71]
after hitting command 

> php artisan rinvex:publish:categories

i get the error below... .

![image](https://user-images.githubusercontent.com/1050583/77233425-430e1a00-6be2-11ea-92e1-a3b644de2833.png)

Am using 3.0.5 because of using Laravel 6.*
4.* is not an option because im currently using Laravel 6.*

**Comment by flolanger** [comment]
Any news to this? It's happening for me too in Laravel 6.

**Comment by Omranic** [comment]
This issue should be fixed in recent release, please check versions v4.x
