### ISSUE TITLE
Laravel 7.5 Support

### ISSUE THREAD

**Issue by micross** [rinvex/laravel-categories#72]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v7.5.2
    - Conclusion: don't install laravel/framework v7.5.2
    - rinvex/laravel-categories v3.0.0 requires illuminate/database ^6.0.0 -> satisfiable by laravel/framework[6.x-dev],
 illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.
1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6,
v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-categories v3.0.1 requires illuminate/database ^6.0.0 -> satisfiable by laravel/framework[6.x-dev],
 illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.
1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6,
v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-categories v3.0.2 requires illuminate/database ^6.0.0 -> satisfiable by laravel/framework[6.x-dev],
 illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.
1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6,
v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-categories v3.0.3 requires illuminate/database ^6.0.0 -> satisfiable by laravel/framework[6.x-dev],
 illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.
1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6,
v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-categories v3.0.4 requires illuminate/database ^6.0.0 -> satisfiable by laravel/framework[6.x-dev],
 illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.
1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6,
v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-categories v3.0.5 requires illuminate/database ^6.0.0 -> satisfiable by laravel/framework[6.x-dev],
 illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.
1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6,
v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - Can only install one of: laravel/framework[6.x-dev, v7.5.2].
    - don't install illuminate/database 6.x-dev|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.0.0|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.0.1|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.0.2|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.0.3|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.0.4|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.1.0|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.10.0|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.11.0|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.12.0|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.13.0|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.13.1|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.14.0|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.15.0|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.17.1|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.18.0|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.18.1|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.18.2|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.18.3|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.18.4|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.18.5|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.18.6|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.2.0|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.3.0|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.4.1|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.5.0|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.5.1|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.5.2|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.6.0|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.6.1|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.6.2|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.7.0|don't install laravel/framework v7.5.2
    - don't install illuminate/database v6.8.0|don't install laravel/framework v7.5.2
    - Installation request for laravel/framework (locked at v7.5.2, required as ^7.0) -> satisfiable by laravel/framework[v7.5.2].
    - Installation request for rinvex/laravel-categories ^3.0 -> satisfiable by rinvex/laravel-categories[v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5].

**Comment by fernas** [comment]
Any news on Laravel 7.x support?

**Comment by qindj** [comment]
ref #67

**Comment by Omranic** [comment]
Hello, thank you for your feedback.

Yes, this package fully supports Laravel 7.x already, it requires PHP 7.4 as minimum requirement. If you can't afford that, feel free to form the package for now and lower the minimum PHP version required 🙂 

Stay healthy, stay safe.
