### ISSUE TITLE
Limit 3.0.x to <= php 7.3

### ISSUE THREAD

**Issue by ee01** [rinvex/laravel-categories#73]
Could you please publish a new version 3.0.x to update the dependencies
`"spatie/laravel-sluggable": "~2.2.0",`
Since spatie/laravel-sluggable@2.3.0 requires php 7.4, but our 3.0.x didn't.

**Comment by Omranic** [comment]
The new release v4.x already supports latest versions of dependencies, but also requires PHP v7.4 as a minimum requirement. I hope this helps.

If you're still on an older version of PHP, feel free to fork this package and lower the PHP dependency, and it should work smoothly for you 👍

**Comment by ee01** [comment]
Unfortunately, my server doesn't support php 7.4.

So if there's a version to support laravel-sluggable@~2.2.0 under php 7.3, it would be of great help.
