### ISSUE TITLE
Support for Laravel v7.10.3

### ISSUE THREAD

**Issue by marcwitteveen** [rinvex/laravel-categories#74]
Does not seem to work with the latest version of Laravel

Problem 1
    - Conclusion: remove laravel/framework v7.10.3
    - Conclusion: don't install laravel/framework v7.10.3
    - rinvex/laravel-categories v3.0.0 requires illuminate/database ^6.0.0 -> satisfiable by illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-categories v3.0.1 requires illuminate/database ^6.0.0 -> satisfiable by illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-categories v3.0.2 requires illuminate/database ^6.0.0 -> satisfiable by illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-categories v3.0.3 requires illuminate/database ^6.0.0 -> satisfiable by illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-categories v3.0.4 requires illuminate/database ^6.0.0 -> satisfiable by illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - rinvex/laravel-categories v3.0.5 requires illuminate/database ^6.0.0 -> satisfiable by illuminate/database[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - don't install illuminate/database 6.x-dev|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.0.0|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.0.1|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.0.2|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.0.3|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.0.4|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.1.0|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.10.0|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.11.0|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.12.0|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.13.0|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.13.1|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.14.0|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.15.0|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.15.1|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.16.0|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.17.0|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.17.1|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.18.0|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.18.1|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.18.10|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.18.11|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.18.12|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.18.13|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.18.2|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.18.3|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.18.4|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.18.5|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.18.6|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.18.7|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.18.8|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.18.9|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.2.0|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.3.0|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.4.1|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.5.0|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.5.1|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.5.2|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.6.0|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.6.1|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.6.2|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.7.0|don't install laravel/framework v7.10.3
    - don't install illuminate/database v6.8.0|don't install laravel/framework v7.10.3
    - Installation request for laravel/framework (locked at v7.10.3, required as ^7.0) -> satisfiable by laravel/framework[v7.10.3].
    - Installation request for rinvex/laravel-categories ^3.0 -> satisfiable by rinvex/laravel-categories[v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5].

**Comment by marcwitteveen** [comment]
Solved after updating to the latest PHP version and composer.

**Comment by Omranic** [comment]
Glad you made it work, stay safe 🙂
