### ISSUE TITLE
Sort (order) parent categories

### ISSUE THREAD

**Issue by altynbek07** [rinvex/laravel-categories#75]
Hi. Methods `$category->down()` and `$category->up()` works only inside parent category. So, when I build [tree](https://github.com/rinvex/laravel-categories#building-a-tree) how I can sort parent categories? Maybe there is an elegant way?

**Comment by altynbek07** [comment]
I solved this problem. By `$category->down()` and `$category->up()` methods I shifted parent categories, and then I use `defaultOrder()` method when build tree: `$categories = app('rinvex.categories.category')->defaultOrder()->get()->toTree();`

**Comment by Omranic** [comment]
I'm glad it's all sorted now for you, happy coding! :)
