### ISSUE TITLE
Retrieve categories by model `categorizable_type`?

### ISSUE THREAD

**Issue by enkota** [rinvex/laravel-categories#76]
Hi,

I am using a few models with your package and able to retrieve the model entries easy enough with `withCategories()`. However, I am unsure how to list all categories for that particular model?

For example, I'd like to list all categories for the `News::class`. 

Is this possible? I am thinking possibly with `whereHasMorph` to reference the `categorizables` table?

Thanks,
Scott

**Comment by enkota** [comment]
Ended up adding a `category_type` to the `category` table and referenced from there. If there's a better way to achieve this let me know!

**Comment by Omranic** [comment]
Yes, absolutely! That's documented here 
https://github.com/rinvex/laravel-categories#retrieve-all-models-attached-to-the-category

And the code you need is as follows:
```php
$category = app('rinvex.categories.category')->find(1);
$category->entries(\App\Models\Post::class);
```

**Comment by enkota** [comment]
Hey @Omranic - Thanks, this works great for returning based on a single category. What I was meaning was to be able to return all the categories that belong to `\App\Models\Post:class`.

So for example:

```
$category = app('rinvex.categories.category')->get();
$category->entries(\App\Models\Post::class);
```

I'd like to return 

`cat-1`
`cat-2` 
etc.. 

These categories belong to the `'App\Models\Post::class`.

Hope that makes more sense?

Thanks!

**Comment by khalid3bdallah** [comment]
@enkota 
That's documented here
https://github.com/rinvex/laravel-categories#manage-your-categorizable-model
```
// Get instance of your model
$post = new \App\Models\Post::find();

// Get attached categories collection
$post->categories;

// Get attached categories query builder
$post->categories();
```
