### ISSUE TITLE
All categories, withDepth, toFlatTree ? 

### ISSUE THREAD

**Issue by ingageco** [rinvex/laravel-categories#77]
I'm trying to get a flat tree of all categories, but including the depth property. Is this possible? 

I am extending the Rinvex model -which could be the issue. I've tried:

Category::all()->withDepth()->toFlatTree()
Category::withDepth()->get()->toFlatTree()

And some other variations, but no dice. Any advice for getting a flat tree with depth?

**Comment by ingageco** [comment]
Let me follow up by saying that the code below returns results, but only root items: 

app('rinvex.categories.category')->withDepth()->get()->toFlatTree()

**Comment by Omranic** [comment]
The following code is working smoothly as expected, with the results you're looking for, hope it helps, please let me know if you still have any further questions 🙂 
```php
$cats = app('rinvex.categories.category')->withDepth()->defaultOrder()->get()->toArray();
```

**Comment by ingageco** [comment]
Nice! I'll try it out and confirm. Thank you!
