### ISSUE TITLE
On destroy of category, redirect not working

### ISSUE THREAD

**Issue by enkota** [rinvex/laravel-categories#78]
Hey,

Not sure if this is something my end, but when trying to delete a category via a destroy form, it always seems to redirect to the show route after deleting. Ideally, I'd like to redirect to the category index and not the category show view that was just deleted. If I comment out `$category->delete()` it redirects normally, so seems to be something on this line.

**Form:**
```
<form action="{{ route('admin.categories.destroy', $category->id )}}" method="POST">
    @csrf
    @method('DELETE')
    <button type="submit">Delete</button>
</form>
```

**Destroy Controller:**
```
    public function destroy($id)
    {
        $category = app('rinvex.categories.category')->find($id);
        $category->delete();
        return redirect()->route('admin.categories.index');
    }
```

Any ideas? Thanks!

**Comment by enkota** [comment]
@Omranic Quick Update:

Tried using implicit binding but still seems to always redirect to the show route and not redirect. There is something happening during `->delete()` that's redirecting before the return. Is this maybe related to the automatic detach of records? :

```
    public function destroy(Collection $collection)
    {
        $collection->delete(); //Commenting this out will redirect fine.
        return redirect('admin/base/collections');
    }
```

Update 2: 

Disabling the event for deleted fixes this. Is there any way to stop this happening? Thanks! - 

`use Rinvex\Categories\Events\CategoryDeleted;`

For now I've just overridden this into my `Collection` model:

```
    protected $dispatchesEvents = [
        'saved' => CategorySaved::class,
        // 'deleted' => CategoryDeleted::class,
    ];
```

**Comment by chuysbz** [comment]
I'm using version 4.1 and this problem keeps happening. :(

**Comment by enkota** [comment]
> I'm using version 4.1 and this problem keeps happening. :(

If you can live without events, you can disable them as above. Looks like a bug though I think.

**Comment by Omranic** [comment]
Thank you for your patience, this has been fixed in latest release.
