### ISSUE TITLE
Unable to install on PHP 7.3

### ISSUE THREAD

**Issue by mebron** [rinvex/laravel-categories#81]
Most server providers only support PHP version up to 7.3. Please add support to PHP 7.3 if possible.

**Comment by carpad88** [comment]
I tried to use with a laravel installation v7.16.1 and couldn't install it. So please also add support for Laravel 7.

**Comment by Omranic** [comment]
Thank you for your message, currently we're only supporting PHP v7.4 and up.
If you need older support please use older branch of the package, or feel free to fork it and lower the dependencies :)
