### ISSUE TITLE
[Question] What is the best practice to integrate with "GeneaLabs / laravel-model-caching"

### ISSUE THREAD

**Issue by khalid3bdallah** [rinvex/laravel-categories#82]
I wanted to cache category queries to database. 
I'm using [GeneaLabs/laravel-model-caching](https://github.com/GeneaLabs/laravel-model-caching)
I did the following

```
namespace App;

use GeneaLabs\LaravelModelCaching\Traits\Cachable;
use Rinvex\Categories\Models\Category as RinvexCategory;

class Category extends RinvexCategory
{
    use Cachable;
}
```
Is there any better way to do this? 
Especially that it doesn't cover queries for model related categories like the following
```
$post = new \App\Models\Post::find();
$post->categories;
```

**Comment by Omranic** [comment]
That's correct. You're using it the right way 👍
