### ISSUE TITLE
Laravel 8 compatibility

### ISSUE THREAD

**Issue by afshiney** [rinvex/laravel-categories#85]
Hey there,
Just wanted to know if there will be a Laravel 8 support anytime soon.
Thanks in advance.

**Comment by ghost** [comment]
It requires [kalnoy/nestedset](https://github.com/lazychaser/laravel-nestedset) depency to be released for L8 too. 
I hope soon.

**Comment by sashsvamir** [comment]
> It requires [kalnoy/nestedset](https://github.com/lazychaser/laravel-nestedset) depency to be released for L8 too.
> I hope soon.

**kalnoy/nestedset**  already support L8 

But it requires also to be L8:
- [rinvex/laravel-support](https://github.com/rinvex/laravel-support)
- [felixkiss/uniquewith-validator](https://github.com/felixkiss/uniquewith-validator)

**Comment by squatto** [comment]
Adding this to update the issue and subscribe myself 👍🏻 

* [rinvex/laravel-support](https://github.com/rinvex/laravel-support) has [an open PR](https://github.com/rinvex/laravel-support/pull/38) to support L8 but it has a [failing check](https://travis-ci.org/github/rinvex/laravel-support/builds/725846534)
* [felixkiss/uniquewith-validator](https://github.com/felixkiss/uniquewith-validator) has two (identical) open PRs ([#116](https://github.com/felixkiss/uniquewith-validator/pull/116) and [#118](https://github.com/felixkiss/uniquewith-validator/pull/118)) to support L8

**Comment by tallesairan** [comment]
any updates ?

**Comment by squatto** [comment]
@tallesairan unfortunately, neither of the packages have had any significant updates/releases since my last message. PR [#116](https://github.com/felixkiss/uniquewith-validator/pull/116) on felixkiss/uniquewith-validator was _approved_, but it wasn't _merged_ for some reason. Someone commented 3 days ago asking if it could be merged and a new release made, but nothing has happened yet.

**Comment by tallesairan** [comment]
I also tried to contribute to the progress but I still don't have the necessary skills to create a PR :(

**Comment by squatto** [comment]
@tallesairan I'd be happy to help! Have you made the code changes and you just need to create a PR?

**Comment by dhi2** [comment]
Yes please update soon. Laravel 9 is already in the pipeline.

**Comment by enkota** [comment]
> Yes please update soon. Laravel 9 is already in the pipeline.

Believe we are stuck until this [PR](https://github.com/felixkiss/uniquewith-validator/pull/116) dependancy is pushed.

**Comment by abmohajeri** [comment]
any updates?

**Comment by enkota** [comment]
@Omranic - What do you suggest happens with updates if we have no response from your [dependency](https://github.com/felixkiss/uniquewith-validator/pull/116)?

**Comment by dom235** [comment]
push ✨

**Comment by namsir** [comment]
this is nightmare.

**Comment by enkota** [comment]
> this is nightmare.

I've ended up dropping the package and using https://github.com/lazychaser/laravel-nestedset directly. Take a look at [this package](https://github.com/AliBayat/Laravel-Categorizable) for ideas on setting it up for categories. Took me about a day to migrate it. Best of luck!

**Comment by namsir** [comment]
> > this is nightmare.
> 
> I've ended up dropping the package and using https://github.com/lazychaser/laravel-nestedset directly. Take a look at [this package](https://github.com/AliBayat/Laravel-Categorizable) for ideas on setting it up for categories. Took me about a day to migrate it. Best of luck!

YOU ARE THE HERO SIR :) thanks a mil.

**Comment by dom235** [comment]
First off, what i did, i wrote an kind email directly to rinvex without a response.

In case it could help anyone too. Here is my solution which has a few downsides and is not perfect at all.

1. Modify your composer.json

```
"autoload": {
        "psr-4": {
....
            "Rinvex\\": "support/rinvex"
        },
    },
```

2. Create a directory /support/rinvex or anything you would like
3. Move the src Code from rinvex packages into their corresponding directory ( /support/rinvex/Categories|Subscriptions|Support)
4. Decide if you want to keep rinvex model validation (I removed it). You might have to do some more work here too to get it working (e.g. you'll need another third party dependency)
5. Integrate every dependency that any rinvex package use in your composer.json (like spatie/laravel-sluggable, kalnoy/nestedset, ...)
6. Run your tests, if you don't have any, write them.

My win for this solution, i don't have to modify my existing source code and can leave it, as it is. For instance, i'm mostly subclassing package models like seen below

```
<?php

namespace App\Shared\Models;

class Category extends \Rinvex\Categories\Models\Category
{
}
```

I don't like this approach but when rinvex comes back i can easily switch back and re-run my tests.

Good luck everyone in surviving this nightmare

PS: same as : https://github.com/rinvex/laravel-subscriptions/issues/117

**Comment by nguyendatdh93** [comment]
I also take care this issue.

**Comment by Omranic** [comment]
Hello, thank you for your patience, this is now done! Check latest release!!

This package now supports Laravel v8, PHP v8, Composer v2, enjoy 🥳

CC @nguyendatdh93 @schranzer235 @namsir @enkota @abmohajeri @dhi2 @squatto @tallesairan @sashsvamir @Wikiki @afshiinasghari
