### ISSUE TITLE
Question: Best practice to make categories per user

### ISSUE THREAD

**Issue by nilskretschmer** [rinvex/laravel-categories#95]
Hi,
thanks for this awesome library. I'd like to use it in an upcoming project. But I need to make some little adjustments.

What I want to achieve:
Each user has its own categories - so as I understand I'd need to adjust the table structure/migrations for this.

Or is there another way by not touching the logic of this library to achieve categories per user?

Thank you

**Comment by Omranic** [comment]
Probably yes, you'll need to adjust both migrations and model to achieve that.

You can publish your config & migration files using `php artisan rinvex:publish:categories`, disable migrations autoload, and override the model in config file https://github.com/rinvex/laravel-categories/blob/master/config/config.php#L8
