### ISSUE TITLE
get list from child to parent

### ISSUE THREAD

**Issue by pishguy** [rinvex/laravel-categories#97]
is there any implementation to get tree from child to parent?

**Comment by Omranic** [comment]
Yes, if I understand correctly, this would be your answer https://github.com/lazychaser/laravel-nestedset#building-a-tree

This package is based on [lazychaser/laravel-nestedset](https://github.com/lazychaser/laravel-nestedset), check it out for more details about the nodes manipulation.

If that's not what you need, please explain in more details so I can help you better.
